<?php

namespace ViMagento\Shop\Controller\Product;

use Magento\Catalog\Controller\Product\View as CatalogView;

class View extends CatalogView
{
    // Overriden in order to add new layout handle in case product page is loaded in iframe
    public function execute()
    {
        if($this->getRequest()->getParams("iframe")){
            $layout = $this->_view->getLayout();
            $layout->getUpdate()->addHandle('shop_product_view');
        }
        return parent::execute(); // TODO: Change the autogenerated stub
    }
}
